### ISSUE TITLE
Database as data source

### ISSUE THREAD

**Issue by wkk1020** [CorpGlory/grafana-progress-list#35]
I'm trying to write a query to provide the output for this plugin, how should the query like?

**Comment by rozetko** [comment]
Hi, @wkk1020! You should get 1 or 2 fields from your database formatted as _Time Series_.

If you get 1 field - you can use only _total_ aggregate function (available at Options -> Mapping -> Stat).

If you get 2 fields (key and value respectively) - any aggregate function can be used.

![image](https://user-images.githubusercontent.com/1989898/35440847-41f2479a-02b2-11e8-9b70-1a243d197f50.png)

P.S. you can find examples in [documentation](https://github.com/CorpGlory/grafana-progress-list/wiki).

P.P.S. if you see nothing after writing query - make sure you have right time range chosen (at top-right corner of screen).

**Comment by nekenk1** [comment]
Any idea how to use it with Prometheus ? I just want to have the progress for few labels but Prometheus returns one timeseries for each label while this plugin seems to accept only a unique timeseries with label-value as the metric data.

**Comment by rozetko** [comment]
Hi, @alexvaut 

Here is the example of Prometheus datasource usage:

![image](https://user-images.githubusercontent.com/1989898/68961477-88a97900-07e3-11ea-8216-ea41f18694d7.png)

It works with "Mapping type: target to datapoint" set in plugin settings.

![image](https://user-images.githubusercontent.com/1989898/68961259-0751e680-07e3-11ea-8181-08cc96d0f07e.png)

**Comment by jonyrock** [comment]
Is it actual? @rozetko

**Comment by rozetko** [comment]
Looks like it's not
