### ISSUE TITLE
Works with Mysql or ES Datasource?

### ISSUE THREAD

**Issue by karnamonkster** [CorpGlory/grafana-progress-list#36]
Hi,
I am trying to display records from Elasticsearch as Data source, this is with a timestamp.
however i do not see the options in the metrics tab as specified by you in the readme.
Any help would be highly appreciated.
Also with my MYSQL  database i am trying to query some records with no timestamp, just wanted to know whether that works or not?

**Comment by jonyrock** [comment]
hey @karnamonkster it's not possibel to use mysql, we haven't tries ES . 
I encourage you to try to find a way how to get same output as in https://github.com/CorpGlory/grafana-progress-list/wiki
just look what your chrome->dev tool-> network returns from "legit" queries.

If you really need this feature, we can consider development of it

**Comment by amper43** [comment]
@karnamonkster now progress list supports both mysql and elasticsearch

**Comment by edum18** [comment]
@amper43 What about MSSQL? I'm not being able to do a working example

**Comment by rozetko** [comment]
Hi @edum18, MSSQL should work as well as MySQL. 

Please attach your SQL query. Maybe it needs to be changed to get data in the appropriate format.

P.S. This comment might help: https://github.com/CorpGlory/grafana-progress-list/issues/35#issuecomment-554447427.
