### ISSUE TITLE
"Instance Name" (example HD Name C: D: etc.) for "name" possible?

### ISSUE THREAD

**Issue by StefanSa** [CorpGlory/grafana-progress-list#37]
Thank you for this interesting plugin.
have a metric set win_disk from telegraph here.
Is there a chance to use the "Instancen Name" (HD Name C: D: etc.) for "name"?

**Comment by jonyrock** [comment]
Hey @StefanSa 

Can I ask you to make a screenshot with explanation, please? 
Not sure I understand your goal.

**Comment by StefanSa** [comment]
Hi (privjet) @jonyrock 
i would like to achieve that, example with Kibana.
![need](https://user-images.githubusercontent.com/6105075/49723857-31f8fe00-fc68-11e8-95e4-1bf3446e2409.png)

Currently i try this here, but without success.
![test](https://user-images.githubusercontent.com/6105075/49723932-62409c80-fc68-11e8-95f6-52877be1eb5e.png)

`SELECT "/^{C:,D:,E:,F:,G:,H:}$/", "Percent_Free_Space" FROM "win_disk" WHERE ("host" =~ /^SFG24$/ AND "instance" =~ /^(C:|D:|E:|F:|G:|H:)$/) AND time >= now() - 3h and time <= now() - 30s`

What am i doing wrong here?

**Comment by jonyrock** [comment]
@rozetko may I ask you to help there, please

**Comment by jonyrock** [comment]
@StefanSa is it urgent?

**Comment by jonyrock** [comment]
@StefanSa I think you can do that, but I need some time for response if @rozetko will not be available.

**Comment by StefanSa** [comment]
@jonyrock 
Hi Alex,
Thank you for your help.
It is not so urgent, it is important that it works.

Привет в россию

**Comment by rozetko** [comment]
Hey, @StefanSa!
Your query should work in case it returns any data
Can I ask you to show your `Query inspector` contents?
![image](https://user-images.githubusercontent.com/1989898/49808329-57bbfb00-fd6d-11e8-9f10-f745eb0f37bb.png)
Interested in highlighted fields

P.S. If you have empty results field - please try to change dashboard time range

**Comment by rozetko** [comment]
Hey, @StefanSa 
The problem is - you have `Instance Name` as a column name
But it should exist as a value for each timestamp

Proper measurement example
```
time,Instance_Name,Percent_Free_Space
1544606410000,C:/,63
1544606410000,D:/,20
1544606420000,C:/,64
1544606420000,D:/,20
```

**Comment by rozetko** [comment]
@StefanSa as far as I see in your query - you have `instance` field in your measurement
Changing `field(/^$disk$/)` to `field(instance)` in your query should do the thing

**Comment by StefanSa** [comment]
@rozetko
that will not work like that, "instance" is not a field.
![mes](https://user-images.githubusercontent.com/6105075/49880362-4980e400-fe2c-11e8-9543-938af6dd8c21.png)

**Comment by rozetko** [comment]
I've just tested and it works at my instance

![image](https://user-images.githubusercontent.com/1989898/49881373-3e837f00-fe3f-11e8-8b4b-c3e37b04249b.png)
Have `type_instance` as tag also
Tags are not shown in `field()` dropdown, but you can type it there manually

**Comment by StefanSa** [comment]
@rozetko
OK,
`values:Array[1077]
0:Array[1544619770000,63.56344223022461,C:]
1:Array[1544619780000,63.56344223022461,C:]
2:Array[1544619791000,63.56344223022461,C:]
`
But grafana complains (field:instance)
Got non-numberic value: C:

**Comment by rozetko** [comment]
@StefanSa 
Plugin depends on fields' order
You should swap `instance name` and `free space` fields so that response looks like `Array[1544619770000,C:,63.56344223022461]...` etc

**Comment by StefanSa** [comment]
@rozetko
i changed orders and now get a bar displayed, but show 100%
`values:Array[1077]
0:Array[1544620370000,C:,63.57817459106445]
1:Array[1544620380000,C:,63.57817459106445]
2:Array[1544620390000,C:,63.57817459106445]`

**Comment by rozetko** [comment]
@StefanSa 
If you want to get current percentage - you can change options like this
![image](https://user-images.githubusercontent.com/1989898/49883134-14cc5700-fe43-11e8-8b22-e0dd85bd6269.png)

**Comment by rozetko** [comment]
@StefanSa Glad to help!

**Comment by StefanSa** [comment]
@rozetko 
Sorry, but see another problem.

wrong:
![falsch](https://user-images.githubusercontent.com/6105075/49885541-cd8c9900-fe37-11e8-80a3-ece1cb4a438b.png)

correct:
![correct](https://user-images.githubusercontent.com/6105075/49885576-ef861b80-fe37-11e8-8dcb-a56643eb3f7d.png)
