### ISSUE TITLE
If there is "one" bar, the threshold is displayed incorrectly

### ISSUE THREAD

**Issue by StefanSa** [CorpGlory/grafana-progress-list#38]
Hi
@rozetko, @jonyrock
have the following problem.
If there is "one" bar, the threshold is displayed incorrectly.

wrong:
![falsch](https://user-images.githubusercontent.com/6105075/49886467-ff066400-fe39-11e8-8d42-dfedc997c0e0.png)

correct:
![correct](https://user-images.githubusercontent.com/6105075/49886480-075e9f00-fe3a-11e8-8761-594da01d845f.png)

**Comment by StefanSa** [comment]
Any chance to solve the problem, or am i doing something wrong here?

**Comment by jonyrock** [comment]
@StefanSa sorry, mate, we a bit busy these days :( Will ping you here soon

**Comment by StefanSa** [comment]
@jonyrock 
Sorry, извините
That was not your fault, i  just have to read your documentation correctly.
![richtig](https://user-images.githubusercontent.com/6105075/49990837-5d892a80-ff7f-11e8-9c3d-4980290653d6.png)

The solution was "Value Type" from shared to percent and "Max Value 100"
If we do not read / hear this year, then you have a happy new year. -> с новым годом

Привет в россию
