### ISSUE TITLE
Progress list crashes dashboard with Table data

### ISSUE THREAD

**Issue by corpglory-dev** [CorpGlory/grafana-progress-list#48]
Progress list crashes dashboard when your query has "Table" format, not "Time series"

![image](https://user-images.githubusercontent.com/47055832/81965315-8d2edd00-9620-11ea-916a-6958bb761a5d.png)

**Comment by jonyrock** [comment]
We show an error in such cases now, introduced in https://github.com/CorpGlory/grafana-progress-list/pull/56
