### ISSUE TITLE
Bad input plugin crash in Grafana 6+

### ISSUE THREAD

**Issue by corpglory-dev** [CorpGlory/grafana-progress-list#51]
Steps to reproduce:
- create dashboard
- add progress-list panel
- add query with wrong output format

Expected behaviour:
- exclamation mark with error message (as in Grafana 5)

Actual behaviour:
- dashboard crashes

![image](https://user-images.githubusercontent.com/47055832/89177522-608dc000-d594-11ea-84c5-13fc34b73219.png)

**Comment by jonyrock** [comment]
I think we should add link to https://github.com/CorpGlory/grafana-progress-list/wiki when we show error about a bad query/response format

**Comment by jonyrock** [comment]
To reproduce this on prometheus, for example, you can do following:

* create query to prometheus `go_memstats_heap_released_bytes`
* select Options -> Stat -> Min

like on screenshot:

![image](https://user-images.githubusercontent.com/1022757/96335377-7fbaca80-1078-11eb-96d5-06064d474f3f.png)

**Comment by jonyrock** [comment]
Together with notification I would also show message like the default graph "no data", but about the bad response format:

![image](https://user-images.githubusercontent.com/1022757/96338355-a6373080-108d-11eb-92dc-b04c887382b0.png)
